---
- name: Report action
  debug: msg="Storage action {{storage_action}}, iSCSI folder {{ env_pripath_iscsi }}."

- name: Check if environments folder exists
  stat: path="{{ env_pripath_iscsi }}{{ env_name_clean }}"
  register: pathretval

- name: Report environment path found
  debug: msg="Storage path {{ env_pripath_iscsi }}{{ env_name_clean }} found{{":"}} {{ pathretval.stat.exists }}"

- name: Check if fingerprint file exists
  stat: path="{{ env_pripath_iscsi }}{{ env_name_clean }}/{{ env_uuid }}"
  register: fprintretval

- name: Report fingerprint file
  debug: msg="Fingerprint file {{ env_pripath_iscsi }}{{ env_name_clean }}/{{ env_uuid }} found{{":"}} {{ fprintretval.stat.exists }}"

- name: Fail if folder exists but is not owned by this environment
  fail: msg="Folder {{ env_pripath_iscsi }}{{ env_name_clean }} exists but is owned by a different environment."
  when: ( pathretval.stat.exists | trim  == "True" ) and ( fprintretval.stat.exists | trim =="False"  )

- block:

  - name: Targetcli - remove iscsi target
    shell: targetcli iscsi/ delete {{ env_iscsi_target }}:{{ env_uuid }}

  - name: Targetcli - remove backstores
    shell: targetcli backstores/fileio/ delete {{ item }}
    with_items:
      - "{{ env_pripools }}"

  - name: Targetcli - remove quorum
    shell: targetcli backstores/fileio/ delete {{ env_name_clean }}-quorum
    when: env_hv == "kvm"
    ignore_errors: true

  - name: Targetcli - check config
    shell: targetcli iscsi/{{ env_iscsi_target }}:{{ env_uuid }} ls
    register: targetconfig

  - name: Report targetcli configuration
    debug: msg={{ targetconfig.stdout }}

  - name: Delete fingerprint file
    file: path={{ env_pripath_iscsi }}{{ env_name_clean }}/{{ env_uuid }} state=absent

  - name: Delete environments folder
    file: state=absent path={{ env_pripath_iscsi }}{{ env_name_clean }}

  - name: Report deleted folder
    debug: msg="Folder {{ env_pripath_iscsi }}{{ env_name_clean }} removed."

  when: ( pathretval.stat.exists | trim  == "True" ) and ( fprintretval.stat.exists | trim =="True" )
